version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASSWORD=yourpassword
      - DB_NAME=board_game_db
    depends_on:
      - db
    command: /bin/bash -c "npm install && npm start"

  db:
    image: mariadb:latest
    environment:
      - MARIADB_USER=app
      - MARIADB_PASSWORD=yourpassword
      - MARIADB_ROOT_PASSWORD=yourpassword
      - MARIADB_DATABASE=board_game_db
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:
